### PR TITLE
Changed find_auxiliary_channels to return unicode

### LINKED ISSUE #53: find_max_significance function is truncating channel names
Auxiliary channel names are still being sliced in my Hveto run which leads to a KeyError when you try to refer to the auxiliary channel dictionary.

In the `find_max_significance` function: https://github.com/hveto/hveto/blob/master/hveto/core.py#L163

The line,
`rec = stack_arrays([primary] + auxiliary.values(), usemask=False,asrecarray=True, autoconvert=True)`
seems to be converting the name of each auxiliary channel to have the same number of characters as the primary channel.

Example output:

```
In [15]: rec
Out[15]: 
rec.array([ (1159777938.4375, 64.82205200195312, 6.263309955596924, u'L1:GDS-CALIB_STRAIN'),
 (1159778139.128906, 503.4388427734375, 6.23298978805542, u'L1:GDS-CALIB_STRAIN'),
 (1159778141.105468, 38.02714920043945, 6.714660167694092, u'L1:GDS-CALIB_STRAIN'),
 ..., (1159799329.0439453, 100.0, 10.0, u'L1:SUS-PR2_M3_MASTE'),
 (1159799333.4711914, 100.0, 10.0, u'L1:SUS-PR2_M3_MASTE'),
 (1159799333.6376953, 100.0, 10.0, u'L1:SUS-PR2_M3_MASTE')], 
          dtype=[('time', '<f8'), ('frequency', '<f4'), ('snr', '<f4'), ('channel', '<U19')])
```

If you flip the order, the truncation doesn't happen:
```
In [51]: rec2 = stack_arrays(auxiliary.values() + [primary], usemask=False, asrecarray=True, autoconvert=True)

In [52]: rec2
Out[52]: 
rec.array([ (1159777920.553711, 100.0, 10.0, 'L1:SUS-ETMY_L1_MASTER_OUT_UR_DQ_0_DAC'),
 (1159777924.4033203, 100.0, 10.0, 'L1:SUS-ETMY_L1_MASTER_OUT_UR_DQ_0_DAC'),
 (1159777927.3798828, 100.0, 10.0, 'L1:SUS-ETMY_L1_MASTER_OUT_UR_DQ_0_DAC'),
 ...,
 (1159799317.269531, 38.02714920043945, 6.262800216674805, 'L1:GDS-CALIB_STRAIN'),
 (1159799319.789062, 504.7231750488281, 6.5116801261901855, 'L1:GDS-CALIB_STRAIN'),
 (1159799324.429687, 504.7231750488281, 12.190750122070312, 'L1:GDS-CALIB_STRAIN')], 
          dtype=[('time', '<f8'), ('frequency', '<f4'), ('snr', '<f4'), ('channel', 'S42')])
```

This still seems like a failure mode even if the order is flipped, a short auxiliary channel name would truncate the name of the primary channel.

### PR DESCRIPTION
**Pull request by tjma12**
Changes the output of `find_auxiliary_channels` to return unicode strings, which matches the ConfigParser channel reading and fixes #53 when calling stack_arrays.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@tjmassin, since we have complete control over how entries are added to the `set()` that gets returned, I would either cast to unicode in each `out.add()` all, or in the `return sorted()` call, rather than creating a new list just for this op.

**Comment by tjma12** [comment]
Ok, I did it this way because the list comprehension won't try to cast unicode to unicode and throw an error and it doesn't care about whether a cache was used or not, but I should be able to add the same logic inside of each loop if you want.

**Comment by duncanmmacleod** [comment]
I would recommend something like

```python
            out.add(u'%s:%s' % ...)
```

or something similar. Also, the `unicode` builtin was removed in python3, so shouldn't be used if possible in python27.

**Comment by tjma12** [comment]
Ah thanks, I didn't realize it had been deprecated. Using the `u` prefix also doesn't throw an error if you try to apply to to something that's already unicode like the `unicode` function does, so the list comprehension isn't as necessary. Tested and updated PR.

**Pull request merged**
