### PR TITLE
Handle null analysis gracefully

### LINKED ISSUE #17: hveto crashes upon making summary plots if no rounds are completed
The `hveto` executable raises a `NameError` if exactly zero rounds were completed above the minimum significance:

```
[hveto 1145311502]    DEBUG: Making summary figures...
Traceback (most recent call last):
  File "/home/duncan.macleod/opt/gwpysoft-2.7/bin/hveto", line 487, in <module>
    label1='Before round 1', label2=afterl, xlabel=statlabel,
NameError: name 'afterl' is not defined
```

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR fixes #17 by exiting the analysis early under any of the following
    
- no active segments found for analysis-flag (zero livtime)
- no triggers found for primary channel
- no rounds with significance above threshold
    
This also includes an HTML stub with an alert div highlighting why there are no results, e.g. when there are no rounds above threshold:

image

**This analysis result was faked for testing purposes**

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@jrsmith02, can you comment on the above image looking like what you want?

**Comment by duncanmmacleod** [comment]
@areeda, @jrsmith02: the early exits introduced by this PR exit with code 0 currently, please advise on the correct exit code for each of the listed cases.

**Comment by areeda** [comment]
Status codes are a good question.  It's always bothered me a bit when the summary pages say  hveto made a mistake  when there is a perfectly valid reason for not producing a result. Such as no triggers produced, no round having high enough significance,… 

 in the previous version the scripts that control the condo jobs would look at the return status from the various stages and create the appropriate HTML if necessary. TNo sat worked fairly well except that the summary pages never knew how the job complete. 

It might work better if each stage wrote out a status file gets used to generate the HTML and the summary page.

**Comment by duncanmmacleod** [comment]
@areeda, I think you're suggestion that all of the above cases should exit cleanly with code 0, since they are all valid null results, either that or the upstream trigger production broke - which isn't hveto's fault.

With the new HTML setup, my summary pages would just pick up the hveto output regardless of results and dump it in.

**Comment by jrsmith02** [comment]
I really like the new output html with error messages.

**Comment by duncanmmacleod** [comment]
@jrsmith02, if you're happy with the changes, there are conflicts with something else I developed, so I can merge it manually.

**Comment by jrsmith02** [comment]
I am happy with the changes, please merge it manually.

**Pull request merged**
